#-*- coding: utf-8 -*-
"""
Django settings for portality project.

Generated by 'django-admin startproject' using Django 1.8.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import json
from collections import namedtuple

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/
try:
    with open(os.path.join(BASE_DIR, "secrets.json")) as f:
        data = json.loads(f.read())
    SecretsNamedTuple = namedtuple('SecretsNamedTuple', data.keys(), verbose=False)
    secrets = SecretsNamedTuple(*[data[x] for x in data.keys()])
    SECRET_KEY = getattr(secrets, "SECRET_KEY")
except IOError:
    SECRET_KEY = 'k8n13h0y@$=v$uxg*^brlv9$#hm8w7nye6km!shc*&bkgkcd*p' # test key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
if (os.environ.has_key('DJANGO_DEBUG')):
    if (os.environ['DJANGO_DEBUG'] == 'Debug'):
        DEBUG = True

ALLOWED_HOSTS = ['gencode.me', 'localhost',]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'giza',
    'issue',
    'rest_framework'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'portality.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'issue.context_processors.global_settings',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'portality.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.postgresql_psycopg2',
         'NAME': 'genonfire',
         'USER': 'genonfire',
         'PASSWORD': '1234',
         'HOST': 'localhost',
         'PORT': '',
    }
}

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/assets/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_URL = '/upload/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload')

LOGIN_REDIRECT_URL = 'login'

# Setting for issue
FILTER_DATE_DELTA = 7 # 핫이슈에 개제될 시간(일)
HOTISSUE_LIMIT = 20 # 핫이슈 리스트 개수
MEDIA_CHOICE = ( # 매체 종류
         ('1', '조선일보'),
         ('2', '중앙일보'),
         ('3', '동아일보'),
         ('4', '한겨레'),
         ('5', '경향신문'),
         ('6', '오마이뉴스'),
         ('7', '미디어오늘'),
         ('8', 'KBS'),
         ('9', 'MBC'),
         ('10', 'SBS'),
         ('11', 'TV조선'),
         ('12', '채널A'),
         ('13', 'JTBC'),
         ('14', 'MBN'),
         ('15', 'YTN'),
         ('16', '연합뉴스'),
         ('17', '뉴시스'),
         ('18', '뉴스1'),
         ('19', '국민일보'),
         ('20', '노컷뉴스'),
         ('21', '뉴데일리'),
         ('22', '뉴스타파'),
         ('23', '뉴스토마토'),
         ('24', '뉴스핌'),
         ('25', '데일리안'),
         ('26', '매일경제'),
         ('27', '머니투데이'),
         ('28', '문화일보'),
         ('29', '민중의소리'),
         ('30', '서울신문'),
         ('31', '세계일보'),
         ('32', '시사iN'),
         ('33', '시사저널'),
         ('34', '위키트리'),
         ('35', '이데일리'),
         ('36', '쿠키뉴스'),
         ('37', '프레시안'),
         ('38', '한국경제'),
         ('39', '한국일보'),
    )